#!/usr/bin/env python2
import click
from scapy.all import *
from config import channelFrequencies
from helper import changeToMonitorMode, changeFrequency, changeToManagedMode, droneDetection

@click.group()
def cli():
	pass

@cli.command()
@click.option('-c', '--channel', default=1, help="Wifi channel number to listen on")
@click.argument('interface')
def static(interface, channel):
	changeToMonitorMode(interface)
	changeFrequency(interface, channel)
	sniff(iface=interface, prn=droneDetection)

@cli.command()
@click.argument('interface')
def hop(interface):
	changeToMonitorMode(interface)
	while True:
		for key in sorted(channelFrequencies.keys()):
			changeFrequency(interface, key)
			sniff(iface=interface, prn=droneDetection, timeout=1)	

@cli.command()
@click.argument('interface')
def managed(interface):
	changeToManagedMode(interface)


if __name__ == '__main__':
	cli()